### PR TITLE
resolve chrome/v8 deoptimization issue related to Function.prototype.apply and arguments

### PR DESCRIPTION
**Pull request by mutsys**
addresses the performance problems discussed in #110. these changes provide v8 with sufficient  visibility into the elements of `arguments`, to allow it to optimize functions that follow a coding pattern that occurs frequently within d3:

## before

```js
export function example(foo, bar) {
  return function() {
    var v = bar.apply(this, arguments);
  }
}
```

## after

```js
export function example(foo, bar) {
  return function() {
    var args = new Array(arguments.length);
    for (var i = 0, l = arguments.length; i < l; i++) {
      args[i] = arguments[i];
    }
    var v = bar.apply(this, args);
  }
}
```

copying the elements of `arguments` to a new array prior to using it as the second argument to `Function.prototype.apply` resolves the issue and allows v8 to optimize the function once and continue to use the optimized code in subsequent invocations.

### CODE REVIEW

**Comment by curran** [comment]
@mutsys The optimization seems like a big win!

One thing that strikes me is the huge amount of duplication in the code. Might it make sense to encapsulate the optimization, maybe something like this:

```js
function toArray(args){
  var arr = new Array(args.length);
  for (var i = 0, l = arguments.length; i < l; i++) {
    arr[i] = args[i];
  }
  return arr;
}
```

It would introduce another level of function invocation, but would be a win for code cleanliness. Then again, I'm not 100% sure the optimization would still come into effect with this approach, as you'd need to invoke it with `toArray(arguments)`.

Also, I'd be curious to see how much of a performance win this is, given that these instances are mostly coupled with DOM manipulation operations (e.g. `this.setAttribute(name, v);`), which might make the impact of the optimization negligible. Do you have any benchmarks you could share that would quantify the practical performance impact of these changes?

**Comment by mbostock** [comment]
You have to inline it; if you pass the `arguments` to another function it again prevents optimization.

**Comment by mutsys** [comment]
@curran Yes, it turns out that this is potentially a significant improvement, considering that the "join" pattern is at the heart of `d3` repeatedly invoking `attr` with a high frequency. I will spend some time this evening to produce some hard data to back this up. In the meanwhile, if you take a look at #110 where I first reported the issue, you will see my initial measurement of the impact on a single invocation.

**Comment by mbostock** [comment]
Closing to inactivity.

**Pull request closed without merging**
