### PR TITLE
Added function to reverse a sub-selection

### PR DESCRIPTION
**Pull request by LaurentGoderre**
Effectivily returns the opposite selection returned by a filter call

Implements #138

### CODE REVIEW

**Comment by mbostock** [comment]
This will throw an exception if *this* selection has fewer groups than the argument selection.

More critically, like *selection*.merge, this requires the *this* selection and the argument selection have the same structure; I would like to improve the design of *selection*.merge to fix this, but I don’t know how. And unlike *selection*.merge I am not sure what the use case is here.

It seems like maybe you want to partition a selection into two groups, rather than filtering it. Conceivably you might want to partition a selection into more than two groups; should that be supported, too?

The current way of doing this would be to filter the same selection more than once. This is more expensive and more verbose, but usually it is a reasonable solution (and I like to avoid additional API if there is already a reasonable way of doing something).

**Comment by LaurentGoderre** [comment]
This is so that if you filter a selection, you can easily get the exact opposite of that filter so that you can affect change on those two sub-selection. Splitting it further than in 3 might be another use case but one that is significantly more complex than this one.

This is just a reverse filter so that you don't have to code it each time.

**Comment by mbostock** [comment]
It doesn’t work with *selection*.filter though, because that removes non-passing elements rather than recording them as nulls. I appreciate you want to make this use case easier; I am concerned that this is too specific a definition.

**Comment by LaurentGoderre** [comment]
I updated it to work with filter (as well as the test)

**Comment by LaurentGoderre** [comment]
@mbostock If you think that breaking a selection into parts is a better use case, I could change this to a function that accepts multiple selections and returns an array of selection for each of them plus another one that contains the remainder. This would cover the invert use case as well as other ones.

**Comment by mbostock** [comment]
Thanks for adding a test. However, the new implementation requires scanning a group group for each element, so it’s probably slower than running the filter again. To compare the proposed approach:

```js
selection1 = selection0.filter("#two");
selection2 = selection0.invert(selection1);
```

And the current approach:

```js
selection1 = selection0.filter("#two");
selection2 = selection0.filter(":not(#two)");
```

The partition approach might work like this:

```js
partitions = selection0.partition("#two"); // {true: [selection], false: [selection]}
selection1 = partitions.true;
selection2 = partitions.false;
```

Another approach would be more boolean set operations:

* *selection*.union(*selection*) (maybe replacing *selection*.merge?)
* *selection*.intersect(*selection*)
* *selection*.difference(*selection*)

I’m not sure if they be that useful in this situation though, and see #89 for a discussion of why it’s a little hard to apply standard set algebra to hierarchical selections.

**Comment by mbostock** [comment]
(In the previous comment I’m not sure whether *selection*.partition should coerce the result of the passed partition function to true or false, and only return an object with two partitions, or if it should coerce the result to a string, and return an object populated by the corresponding string keys. Other possibilities include returning an ES6 Map or a d3.map, or coercing the result to a number and returning an array.)

**Comment by mbostock** [comment]
(There’s also the issue of whether *selection*.partition should behave like *selection*.filter and drop elements, or if it should record them with null.)

**Comment by LaurentGoderre** [comment]
Arguably, my proposed `invert` function is for cases where the filtering is more complicated than a simple selector, for example when using a function for filtering. I meant to introduce that as an option of not running a complexe selection once, then running it again and returning the opposite.

**Comment by mbostock** [comment]
I understand. Is it mostly a matter of wanting less code or faster code?

If you want less code, you can give your filter function a name and call it in two places:

```js
test = d => … some logic …;
selection1 = selection0.filter(d => test(d));
selection2 = selection0.filter(d => !test(d));
```

If you want faster code, you can save the result of your filter function to data, say:

```js
selection0.each(d => d.test = … some logic …);
selection1 = selection0.filter(d => d.test);
selection2 = selection0.filter(d => !d.test);
```

It’s a little dirty to stash this value in the data, of course. If you wanted it to be cleaner I suppose you could use a separate Map object:

```js
test = new Map;
selection0.each(d => test.set(d, … some logic …));
selection1 = selection0.filter(d => test.get(d));
selection2 = selection0.filter(d => !test.get(d));
```

Or equivalently:

```js
test = new Map(selection0.data().map(d => [d, … some logic …]));
selection1 = selection0.filter(d => test.get(d));
selection2 = selection0.filter(d => !test.get(d));
```

**Comment by LaurentGoderre** [comment]
I think it's a bit of both. I saw this as a common pattern but I must have overestimated the simplicity of my solution

**Comment by LaurentGoderre** [comment]
Well I found a different, better way that doesn't require this so closing.

**Comment by LaurentGoderre** [comment]
It was actually your map idea that helped me. I applied to the logic to the data directly. That way the `.enter()` and `.exit()` did the heavy lifting. Made the code a lot simple too.

**Comment by mbostock** [comment]
Sounds great! Thanks for replying.

**Pull request closed without merging**
